# Simple Neural Network

In [1]:
weight = 0.1

In [2]:
def neural_network(input, weight):
    prediction = input * weight
    return prediction

In [3]:
toes = [8.5, 9.5, 10, 9]
input = toes[0]
pred = neural_network(input, weight)
pred

0.8500000000000001

# Multiple Inputs Neural Network

In [4]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output

In [5]:
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

In [6]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

In [7]:
input = [toes[0], wlrec[0], nfans[0]]

In [8]:
weights = [0.1, 0.2, 0]

In [9]:
pred = neural_network(input, weights)

In [10]:
pred

0.9800000000000001

## Multiple Inputs: NumPy version

In [11]:
from __future__ import print_function, division
import numpy as np

In [12]:
weights = np.array([0.1, 0.2, 0])

In [13]:
def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

In [14]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

In [15]:
input = np.array([toes[0], wlrec[0], nfans[0]])

In [16]:
pred = neural_network(input, weights)

In [17]:
pred

0.9800000000000001

# Making a prediction with multiple outputs

In [18]:
weights = [0.3, 0.2, 0.9]

In [19]:
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    
    for i in range(len(vector)):
        output[i] = number * vector[i]
        
    return output

In [20]:
def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

In [21]:
wlrec = [0.65, 0.8, 0.8, 0.9]

In [22]:
input = wlrec[0]

In [23]:
pred = neural_network(input, weights)

In [24]:
pred

[0.195, 0.13, 0.5850000000000001]

# Predicting with multiple inputs and outputs

In [25]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output

In [26]:
def vect_mat_mul (vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
        
    return output

In [27]:
def neural_network(input, weights):
    pred = vect_mat_mul(input,weights)
    return pred

In [28]:
weights = [[0.1, 0.1, -0.3],# hurt?
           [0.1, 0.2, 0.0], # win?
           [0.0, 1.3, 0.1]] # sad?

In [29]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

In [30]:
input = [toes[0], wlrec[0], nfans[0]]

In [31]:
pred = neural_network(input, weights)

In [32]:
pred

[0.555, 0.9800000000000001, 0.9650000000000001]

# Predictions on predictions

In [33]:
        # toes % win # fans
ih_wgt = [[0.1, 0.2, -0.1], # hid[0]
          [-0.1, 0.1, 0.9], # hid[1]
          [0.1, 0.4, 0.1]] # hid[2]

        #hid[0] #hid[1] #hid[2]
hp_wgt = [[0.3, 1.1, -0.3], # hurt?
          [0.1, 0.2, 0.0], # win?
          [0.0, 1.3, 0.1]] # sad?

weights = [ih_wgt, hp_wgt]

In [34]:
def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

In [35]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

In [36]:
input = [toes[0], wlrec[0], nfans[0]]

In [37]:
pred = neural_network(input, weights)
pred

[0.21350000000000002, 0.14500000000000002, 0.5065]

## Numpy version

In [38]:
# toes % win # fans
ih_wgt = np.array([
    [0.1, 0.2, -0.1], # hid[0]
    [-0.1, 0.1, 0.9], # hid[1]
    [0.1, 0.4, 0.1]
]).T # hid[2]

# hid[0] hid[1] hid[2]
hp_wgt = np.array([
    [0.3, 1.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1]
]).T # sad?

In [39]:
weights = [ih_wgt, hp_wgt]

In [40]:
def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

In [41]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

In [42]:
input = np.array([toes[0], wlrec[0], nfans[0]])

In [43]:
pred = neural_network(input,weights)
pred

array([0.2135, 0.145 , 0.5065])

## Numpy Practice

In [44]:
from __future__ import print_function, division
import numpy as np

In [46]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3],
             [4,5,6,7]])
d = np.zeros((2,4))
e = np.random.rand(2,5)

In [48]:
print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.09850366 0.72176451 0.92610601 0.70216946 0.41543008]
 [0.15756831 0.88121267 0.52647889 0.96894768 0.16451336]]


In [49]:
print(a * 0.1)
print(c * 0.2)
print(a * b)
print(a * b * 0.2)
print(a * c)
print(a * e)

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [50]:
a = np.zeros((1,4))
b = np.zeros((4,3))

In [51]:
c = a.dot(b)
c.shape

(1, 3)

In [52]:
a = np.zeros((2,4))
b = np.zeros((4,3))

In [53]:
c = a.dot(b)
c.shape

(2, 3)

In [54]:
e = np.zeros((2,1))
f = np.zeros((1,3))

In [55]:
g = e.dot(f)
g.shape

(2, 3)

In [56]:
h = np.zeros((5,4)).T
i = np.zeros((5,6))

In [57]:
j = h.dot(i)
j.shape

(4, 6)

In [58]:
h = np.zeros((5,4))
i = np.zeros((5,6))

In [59]:
j = h.dot(i)
j.shape

ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)